const icon_by_name = {
    //##Placed Objects
    //## MSC placed objects
    "GreenToken": "GreenToken",
    "WhiteToken": "WhiteToken",
    "Germinator": "Germinator",
    "RedToken": "RedToken",
    "OEsphere": "OEsphere",
    "MSArteryPush": "MSArteryPush",
    "GooieDuck": "Gooieduck_icon",
    "LillyPuck": "Lilypuck_icon",
    "GlowWeed": "Glow_Weed_icon",
    "BigJellyFish": "Giant_Jellyfish_icon",
    "RotFlyPaper": "Rot_icon",
    "MoonCloak": "Cloak_icon",
    "DandelionPeach": "Dandelion_Peach_icon",
    "KarmaShrine": "KarmaShrine",
    "Stowaway": "Stowaway_icon",
    "HRGuard": "Guardian_icon",
    "DevToken": "DevToken",
    //## vanilla placed objects
    "LightSource": "LightSource",
    "FlareBomb": "Flashbang_icon",
    "PuffBall": "Spore_Puff_icon",
    "TempleGuard": "Guardian_icon",
    "LightFixture": "LightFixture",
    "DangleFruit": "Blue_Fruit_icon",
    "CoralStem": "CoralStem",
    "CoralStemWithNeurons": "CoralStemWithNeurons",
    "CoralNeuron": "CoralNeuron",
    "CoralCircuit": "CoralCircuit",
    "WallMycelia": "WallMycelia",
    "ProjectedStars": "ProjectedStars",
    "ZapCoil": "ZapCoil",
    "SuperStructureFuses": "SuperStructureFuses",
    "GravityDisruptor": "GravityDisruptor",
    "SpotLight": "SpotLight",
    "DeepProcessing": "DeepProcessing",
    "Corruption": "Rot_icon",
    "CorruptionTube": "Rot_icon",
    "CorruptionDarkness": "Rot_icon",
    "StuckDaddy": "Rot_icon",
    "SSLightRod": "SSLightRod",
    "CentipedeAttractor": "CentipedeAttractor",
    "DandelionPatch": "DandelionPatch",
    "GhostSpot": "Echo_icon",
    "DataPearl": "Pearl_misc_icon",
    "UniqueDataPearl": "Pearl_misc_icon",
    "SeedCob": "Popcorn_Plant_icon",
    "DeadSeedCob": "Popcorn_Plant_icon",
    "WaterNut": "Bubble_Fruit_icon",
    "JellyFish": "Jellyfish_icon",
    "KarmaFlower": "Karma_Flower_icon",
    "Mushroom": "Mushroom_icon",
    "SlimeMold": "Slime_Mold_icon",
    "FlyLure": "Batnip_Icon",
    "CosmeticSlimeMold": "CosmeticSlimeMold",
    "CosmeticSlimeMold2": "CosmeticSlimeMold2",
    "FirecrackerPlant": "Cherrybomb_icon",
    "VultureGrub": "Vulture_Grub_icon",
    "DeadVultureGrub": "Vulture_Grub_icon",
    "VoidSpawnEgg": "VoidSpawnEgg",
    "ReliableSpear": "Explosive_Spear_icon",
    "SuperJumpInstruction": "SuperJumpInstruction",
    "ProjectedImagePosition": "ProjectedImagePosition",
    "ExitSymbolShelter": "ExitSymbolShelter",
    "ExitSymbolHidden": "ExitSymbolHidden",
    "NoSpearStickZone": "NoSpearStickZone",
    "LanternOnStick": "LanternOnStick",
    "ScavengerOutpost": "ScavengerOutpost",
    "TradeOutpost": "TradeOutpost",
    "ScavengerTreasury": "ScavengerTreasury",
    "ScavTradeInstruction": "ScavTradeInstruction",
    "CustomDecal": "CustomDecal",
    "InsectGroup": "InsectGroup",
    "PlayerPushback": "PlayerPushback",
    "MultiplayerItem": "MultiplayerItem",
    "SporePlant": "SporePlant",
    "GoldToken": "GoldToken",
    "BlueToken": "BlueToken",
    "DeadTokenStalk": "DeadTokenStalk",
    "NeedleEgg": "Noodlefly_Egg_icon",
    "BrokenShelterWaterLevel": "BrokenShelterWaterLevel",
    "BubbleGrass": "Bubble_Weed_icon",
    "Filter": "Filter",
    "ReliableIggyDirection": "ReliableIggyDirection",
    "Hazer": "Hazer_icon",
    "DeadHazer": "Hazer_icon",
    "Rainbow": "Rainbow",
    "LightBeam": "LightBeam",
    "NoLeviathanStrandingZone": "NoLeviathanStrandingZone",
    "FairyParticleSettings": "FairyParticleSettings",
    "DayNightSettings": "DayNightSettings",
    "EnergySwirl": "EnergySwirl",
    "LightningMachine": "LightningMachine",
    "SteamPipe": "SteamPipe",
    "WallSteamer": "WallSteamer",
    "Vine": "Vine",
    "VultureMask": "Vulture_Mask_icon",
    "SnowSource": "SnowSource",
    "DeathFallFocus": "DeathFallFocus",
    "CellDistortion": "CellDistortion",
    "LocalBlizzard": "LocalBlizzard",
    "NeuronSpawner": "Neuron_Fly_icon",
    "HangingPearls": "HangingPearls",
    "Lantern": "Lantern_icon",
    "ExitSymbolAncientShelter": "ExitSymbolAncientShelter",
    "BlinkingFlower": "BlinkingFlower",
    //##End PlacedObjects
    "clear": "00_clear",
    "rock": "Rubbish_icon",
    "spear": "Spear_icon",
    "boomstick": "Explosive_Spear_icon",
    "bomb": "Grenade_icon",
    "hive": "Beehive_icon",
    "lantern": "Lantern_icon",
    "lure": "Batnip_icon",
    "mushroom": "Mushroom_icon",
    "flashbang": "Flashbang_icon",
    "puffball": "10_puffball",
    "waternut": "Bubble_Fruit_icon",
    "firecrackerplant": "Cherrybomb_icon",
    "bluefruit": "Blue_Fruit_icon",
    "jellyfish": "Jellyfish_icon",
    "bubbleweed": "Bubble_Weed_icon",
    "slimemold": "Slime_Mold_icon",
    "NONE": "63_none",
    "None": "63_none",
    "randomitems": "60_randomitems_inactive",
    "Garbage Worm": "Garbage_Worm_icon",
    "Worm Grass": "Worm_Grass_icon",
    "hazer": "Hazer_icon",
    "batfly": "Batfly_icon",
    "vulturegrub": "Vulture_Grub_icon",
    "BigJelly": "Giant_Jellyfish_icon",
    "Overseer": "Overseer_icon",
    //## Creatures
    "Green": "Green_Lizard_icon",
    "Pink": "Pink_Lizard_icon",
    "Blue": "Blue_Lizard_icon",
    "White": "White_Lizard_icon",
    "Black": "Black_Lizard_icon",
    "Yellow": "Yellow_Lizard_icon",
    "Cyan": "Cyan_Lizard_icon",
    "Red": "Red_Lizard_icon",
    "Salamander": "Salamander_icon",
    "CicadaA": "White_Squidcada_icon",
    "CicadaB": "Black_Squidcada_icon",
    "Snail": "Snail_icon",
    "Leech": "Red_Leech_icon",
    "Sea Leech": "Blue_Leech_icon",
    "SeaLeech": "Blue_Leech_icon",
    "Mimic": "Pole_Plant_icon",
    "PoleMimic": "Pole_Plant_icon",
    "Pole Mimic": "Pole_Plant_icon",
    "TentaclePlant": "Monster_Kelp_icon",
    "Tentacle Plant": "Monster_Kelp_icon",
    "Tentacle": "Monster_Kelp_icon",
    "Scavenger": "Scavenger_icon",
    "Vulture": "Vulture_icon",
    "KingVulture": "King_Vulture_icon",
    "King Vulture": "King_Vulture_icon",
    "Small Centipede": "Infant_Centipede_icon",
    "SmallCentipede": "Infant_Centipede_icon",
    "Centipede Small": "Infant_Centipede_icon",
    "Centipede": "Adult_Centipede_icon",
    "Big Centipede": "Overgrown_Centipede_icon",
    "Red Centipede": "Red_Centipede_icon",
    "RedCentipede": "Red_Centipede_icon",
    "Centiwing": "Centiwing_icon",
    "grappleworm": "Grapple_Worm_icon",
    "Tube": "Grapple_Worm_icon",
    "TubeWorm": "Grapple_Worm_icon",
    "Tube Worm": "Grapple_Worm_icon",
    "Lantern Mouse": "Lantern_Mouse_icon",
    "Mouse": "Lantern_Mouse_icon",
    "Spider": "Coalescipede_icon",
    "BigSpider": "Big_Spider_icon",
    "Big Spider": "Big_Spider_icon",
    "Bigspider": "Big_Spider_icon",
    "SpitterSpider": "Spitter_Spider_icon",
    "Miros Bird": "Miros_Bird_icon",
    "Miros": "Miros_Bird_icon",
    "Bro": "Brother_Long_Legs_icon",
    "Daddy": "Daddy_Long_Legs_icon",
    "Deer": "Rain_Deer_icon",
    "EggBug": "Eggbug_icon",
    "Eggbug": "Eggbug_icon",
    "Egg Bug": "Eggbug_icon",
    "DropBug": "Dropwig_icon",
    "Dropbug": "Dropwig_icon",
    "DropWig": "Dropwig_icon",
    "Dropwig": "Dropwig_icon",
    "Drop Bug": "Dropwig_icon",
    "BigNeedleWorm": "Adult_Noodlefly_icon",
    "BigNeedle": "Adult_Noodlefly_icon",
    "Needle": "Adult_Noodlefly_icon",
    "SmallNeedleWorm": "Infant_Noodlefly_icon",
    "SmallNeedle": "Infant_Noodlefly_icon",
    "Jet Fish": "Jetfish_icon",
    "JetFish": "Jetfish_icon",
    "Jetfish": "Jetfish_icon",
    "Leviathan": "Leviathan_icon",
    //##MSC
    "Caramel": "Caramel_Lizard_icon",
    "SpitLizard": "Caramel_Lizard_icon",
    "Strawberry": "Strawberry_Lizard_icon",
    "ZoopLizard": "Strawberry_Lizard_icon",
    "Eel": "Eel_Lizard_icon",
    "EelLizard": "Eel_Lizard_icon",
    "Terror": "Mother_Long_Legs_icon",
    "TerrorLongLegs": "Mother_Long_Legs_icon",
    "MotherSpider": "Mother_Spider_icon",
    "Mother Spider": "Mother_Spider_icon",
    "MirosVulture": "Miros_Vulture_icon",
    "Miros Vulture": "Miros_Vulture_icon",
    "Hellbug": "Firebug_icon",
    "HellBug": "Firebug_icon",
    "Firebug": "Firebug_icon",
    "FireBug": "Firebug_icon",
    "ScavengerElite": "Elite_Scavenger_icon",
    "Scavenger Elite": "Elite_Scavenger_icon",
    "EliteScavenger": "Elite_Scavenger_icon",
    "Elite Scavenger": "Elite_Scavenger_icon",
    "Elite": "Elite_Scavenger_icon",
    "Inspector": "Inspector_icon",
    "Yeek": "Yeek_icon",
    "AquaCentipede": "Aquapede_icon",
    "Aquacenti": "Aquapede_icon",
    "AquaCenti": "Aquapede_icon",
    "Aquapede": "Aquapede_icon",
    "JungleLeech": "Jungle_Leech_icon",
    "Jungle Leech": "Jungle_Leech_icon",
    "Train": "Train_Lizard_icon",
    "TrainLizard": "Train_Lizard_icon",
    "HunterDaddy": "Hunter_Long_Legs_icon",
    "ScavengerKing": "Chieftain_Scavenger_icon",
    //## Slugcats
    "SlugNPC": "Slugpup_icon",
    "slugcat": "Slugcat_icon",
    "white": "Survivor_icon",
    "red": "Hunter_icon",
    "yellow": "Monk_icon",
    "gourmand": "Gourmand_icon",
    "artificer": "Artificer_icon",
    "rivulet": "Rivulet_icon",
    "spear": "Spearmaster_icon",
    "saint": "Saint_icon",
    "inv": "Sofanthiel_icon",
}

var requestLock = {};
var lastRequest = null;

function getJsonObject(url, cb, async = true) {
    if (lastRequest != null) lastRequest.abort();
    let request = new XMLHttpRequest();
    lastRequest = request;
    requestLock = {};
    request.requestLock = requestLock;
    request.open('GET', url, async);
    request.onreadystatechange = function () {
        if (request.requestLock != requestLock && request.status != 0) {
            request.abort();
            console.log("request for " + url + " aborted!");
        }
        else if (request.readyState === 4 && request.status === 200) {
            try {
                cb(JSON.parse(request.responseText));
            } catch (err) {
                console.log(err);
            }
            if (lastRequest == request) lastRequest = null;
        }
    }
    request.send();
}
